[FLOW]
MAX_RUNNERS = 16 # Num. de threads abertas
TASKS_RETURN_EXCEPTION = false # Em caso de exceção nas tasks de requisição, retorna algo em caso de erro (true) ou lança a exceçao (parando a aplicação) (false)
DATE_LOOKBACK = 3 # Dias

[ALLENDPOINTS]
FETCH_MAX_RETRIES=10
FETCH_RETRY_DELAY=3

[TSE]
BASE_URL = "https://cdn.tse.jus.br/estatistica/sead/odsele/"
OUTPUT_EXTRACT_DIR = "output/extract/tse"
TASK_RETRIES = 5
TASK_RETRY_DELAY = 5 # Segundos
TASK_TIMEOUT = 3600 # Segundos
CACHE_POLICY = "INPUTS" # Padrão = INPUTS
CACHE_EXPIRATION = 90 # Dias

[CAMARA]
REST_BASE_URL = "https://dadosabertos.camara.leg.br/api/v2/"
PORTAL_BASE_URL = "https://www.camara.leg.br/"
OUTPUT_EXTRACT_DIR = "output/extract/camara"
TASK_RETRIES = 0
TASK_RETRY_DELAY = 5 # Segundos
TASK_TIMEOUT = 8000 # Segundos
FETCH_LIMIT = 10 # Número de conexões abertas ao mesmo tempo

[SENADO]
REST_BASE_URL = "https://legis.senado.leg.br/dadosabertos/"
OUTPUT_EXTRACT_DIR = "output/extract/senado"
TASK_RETRIES = 0
TASK_RETRY_DELAY = 5 # Segundos
TASK_TIMEOUT = 8000 # Segundos
FETCH_LIMIT = 5 # Número de conexões abertas ao mesmo tempo
